name: SouthPlus签到

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        id: run-script
        shell: pwsh
        env:
          MYPWD: ${{ secrets.PWD }}
          COOKIE: ${{ secrets.COOKIE }}
          UA: ${{ secrets.UA }}
        run: |
          $myPwd = $env:MYPWD
          $cookie = $env:COOKIE
          $ua = $env:UA
          $beijingTime = [DateTimeOffset]::UtcNow.ToOffset([TimeSpan]::FromHours(8)).ToString("yyyy-MM-dd HH:mm:ss")
          Write-Output "$beijingTime"
          $failed = .\script.ps1 -myPwd $myPwd -cookie $cookie -ua $ua
          if ($failed) {
            exit 1
          }
