name: SouthPlus签到

on:
  schedule:
    - cron: "0 0/18 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        id: run-script
        shell: pwsh
        env:
          MYPWD: ${{ secrets.PWD }}
          COOKIE: ${{ secrets.COOKIE }}
          UA: ${{ secrets.UA }}
        continue-on-error: true
        run: |
          $myPwd = $env:MYPWD
          $cookie = $env:COOKIE
          $ua = $env:UA
          $failed = .\script.ps1 -myPwd $myPwd -cookie $cookie -ua $ua
          if ($failed) { exit 1 }

      - name: Retry with Exponential Backoff
        if: steps.run-script.outcome
        shell: pwsh
        env:
          MYPWD: ${{ secrets.PWD }}
          COOKIE: ${{ secrets.COOKIE }}
          UA: ${{ secrets.UA }}
        run: |
          $maxRetries = 10
          $retryCount = 0
          $delay = 180 # 初始延迟时间（3分钟）
          $totalRetryTime = 0
          $maxRetryTime = 3 * 3600 # 最大重试时间（3小时）

          while ($retryCount -lt $maxRetries -and $totalRetryTime -lt $maxRetryTime) {
            Write-Output "重试第 $($retryCount + 1) 次"
            Start-Sleep -Seconds $delay
            $myPwd = $env:MYPWD
            $cookie = $env:COOKIE
            $ua = $env:UA
            $failed = .\script.ps1 -myPwd $myPwd -cookie $cookie -ua $ua
            if (-not $failed) {
              Write-Output "脚本在重试第 $($retryCount + 1) 次成功"
              exit 0
            }
            $retryCount++
            $totalRetryTime += $delay
            $delay = [math]::Min($delay * 2, $maxRetryTime - $totalRetryTime)
          }

          Write-Output "脚本在 $retryCount 次重试后失败"
          exit 1