name: SouthPlus签到

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        id: run-script
        shell: pwsh
        env:
          MYPWD: ${{ secrets.PWD }}
          COOKIE: ${{ secrets.COOKIE }}
          UA: ${{ secrets.UA }}
        run: |
          $myPwd = $env:MYPWD
          $cookie = $env:COOKIE
          $ua = $env:UA
          $beijingTime = [DateTimeOffset]::UtcNow.ToOffset([TimeSpan]::FromHours(8)).ToString("yyyy-MM-dd HH:mm:ss")
          Write-Output "$beijingTime"
          
          # 构建URL
          $url = "https://south-plus.poker-sang.workers.dev/?pwd=$myPwd&cookie=$cookie&ua=$ua"
          
          try {
              # 发送GET请求
              $response = Invoke-WebRequest -Uri $url -Method Get
          
              Write-Output $response.StatusCode
              Write-Output $response.Content
              
              # 检查状态码
              if ($response.StatusCode -notin 200,202) {
                  exit 1
              }
          } catch {
              # 捕获异常并忽略
          }
